spring:
  application:
    name: MerchantSignUp
  profiles:
    active:
    - dev
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
logging:
  level:
    org:
      hibernate:
        SQL:DEBUG
        type:TRACE